### ISSUE TITLE
May I ask what font is used for the prompts in the illustrations in the paper?

### ISSUE THREAD

**Issue by xiefan-guo** [Vchitect/Vlogger#8]
May I ask what font is used for the prompts in the illustrations in the paper?

**Comment by zhuangshaobin** [comment]
Thank you for your interest in our work.

In the pictures in the text, the font used in most prompts is Dreaming Outloud Pro, a font that comes with the ppt.

In the appendix, the font used by the prompt is the default font of the template.

Hope the above can be helpful to you.

**Comment by xiefan-guo** [comment]
thx
